inputs:

{
  config,
  lib,
  pkgs,
  ...
}:

let
  inherit (lib)
    mkIf
    mkDefault
    ;
  cfg = config.programs.aether;

  # Use dotfiles from flake input
  dotfiles = inputs.dotfiles;
in
{
  config =
    let
      quickshellPatched =
        pkgs.runCommand "quickshell-patched"
          {
            buildInputs = [
              pkgs.bash
              cfg.internal.pythonEnv
            ];
          }
          ''
            cp -r ${dotfiles}/dots/.config/quickshell $out
            chmod -R +w $out

            # Replace complex shebangs that patchShebangs can't handle with standard python
            # The complex shebang tried to source a venv, but we provide pythonEnv directly via Nix
            find $out -name "*.py" -print0 | xargs -0 sed -i 's|^#!.*AETHER_VIRTUAL_ENV.*|#!/usr/bin/env python3|'

            patchShebangs $out
          '';
    in
    lib.mkMerge [
      (mkIf cfg.enable {
        # Fake venv for QuickShell scripts to use the Nix python environment
        home.file = {
          ".local/state/quickshell/.venv/bin/activate".text = ''
            # Generated by aether flake
            export VIRTUAL_ENV="${cfg.internal.pythonEnv}"
            export PATH="${cfg.internal.pythonEnv}/bin:$PATH"
            deactivate () {
              # Dummy function for compatibility
              return 0
            }
          '';
          ".local/state/quickshell/.venv/bin/python".source =
            "${cfg.internal.pythonEnv}/bin/python";
          ".local/state/quickshell/.venv/bin/python3".source =
            "${cfg.internal.pythonEnv}/bin/python3";
          ".local/state/quickshell/.venv/pyvenv.cfg".text = ''
            home = ${cfg.internal.pythonEnv}/bin
            include-system-site-packages = false
            version = 3.11.0
          '';
        };

        # Dotfiles management via Home Manager (XDG Config)
        xdg.configFile = {
          "thorium-flags.conf" = {
            force = true;
            source = "${dotfiles}/dots/.config/thorium-flags.conf";
          };
          "xdg-desktop-portal" = {
            force = true;
            source = "${dotfiles}/dots/.config/xdg-desktop-portal";
          };
          "chrome-flags.conf" = {
            force = true;
            source = "${dotfiles}/dots/.config/chrome-flags.conf";
          };
          "code-flags.conf" = {
            force = true;
            source = "${dotfiles}/dots/.config/code-flags.conf";
          };
          "wlogout" = {
            force = true;
            source = "${dotfiles}/dots/.config/wlogout";
          };
          "mpv" = {
            force = true;
            source = "${dotfiles}/dots/.config/mpv";
          };
        };

        # Dotfiles management via Home Manager (XDG Data)
        xdg.dataFile = {
          # and the custom icon is handled here if needed, but it's usually in the package too?
          # Re-adding the single SVG manually just in case
          "icons/hicolor/scalable/apps/aether.svg".source =
            "${dotfiles}/dots/.local/share/icons/aether.svg";
        };

        # Use activation script ONLY for stateful integration
        home.activation.copyIllogicalImpulseConfigs = config.lib.dag.entryAfter [ "writeBoundary" ] ''
          # Path to the config directory in the dotfiles source
          configPath="${dotfiles}/dots/.config"
          targetPath="$HOME/.config"

          # Ensure it's writable even if it exists (for stateful configs)
          function copyIfNotExist {
            local path=$1
            if [ -L "$targetPath/$path" ]; then
                $DRY_RUN_CMD rm "$targetPath/$path"
            fi
            if [ ! -f "$targetPath/$path" ]; then
               if [ -f "$configPath/$path" ]; then
                   $DRY_RUN_CMD cp -r "$configPath/$path" "$targetPath/$path"
                   $DRY_RUN_CMD chmod u+w "$targetPath/$path"
               fi
            else
               $DRY_RUN_CMD chmod u+w "$targetPath/$path"
            fi
          }

          function copyIfReallyNotExist {
            local path=$1
            if [ ! -f "$targetPath/$path" ]; then
               if [ -f "$configPath/$path" ]; then
                   $DRY_RUN_CMD cp -r "$configPath/$path" "$targetPath/$path"
                   $DRY_RUN_CMD chmod u+w "$targetPath/$path"
               fi
            else
               $DRY_RUN_CMD chmod u+w "$targetPath/$path"
            fi
          }

          function givePriv {
            local item=$1
            $DRY_RUN_CMD find $targetPath/$item -type d      -exec chmod u+rwx {} +
            $DRY_RUN_CMD find $targetPath/$item -type f      -exec chmod u+rw {} +
            $DRY_RUN_CMD find $targetPath/$item -name "*.py" -exec chmod +x {} +
            $DRY_RUN_CMD find $targetPath/$item -name "*.sh" -exec chmod +x {} +
          }

          for item in \
            "matugen" \
            "fuzzel"
          do
            if [ -L "$targetPath/$item" ]; then
              $DRY_RUN_CMD rm -r "$targetPath/$item"
            fi
            $DRY_RUN_CMD rm -rf "$targetPath/$item"
            $DRY_RUN_CMD cp -rf "$configPath/$item" "$targetPath/$item"
            givePriv "$item"
          done

          # Hyprland
          $DRY_RUN_CMD mkdir -p $targetPath/hypr/custom
          $DRY_RUN_CMD mkdir -p $targetPath/hypr/hyprland/shellOverrides
          copyIfNotExist "hypr/hyprland/shellOverrides/main.lua"
          copyIfNotExist "hypr/hyprland/colors.lua"
          copyIfReallyNotExist "hypr/custom"

          # Hyprlock
          [ -L "$targetPath/hypr/hyprlock" ] && $DRY_RUN_CMD rm -f "$targetPath/hypr/hyprlock"
          [ -L "$targetPath/hypr/hyprlock/colors.conf" ] && $DRY_RUN_CMD rm -f "$targetPath/hypr/hyprlock/colors.conf"
          $DRY_RUN_CMD mkdir -p $targetPath/hypr/hyprlock
          copyIfNotExist "hypr/hyprlock/colors.conf"

          copyIfNotExist "kdeglobals"

          ${lib.optionalString cfg.copyQuickShellDots ''
            # Quickshell separately (patched derivation)
            [ -L "$targetPath/quickshell" ] && $DRY_RUN_CMD rm -f "$targetPath/quickshell"
            [ -L "$targetPath/quickshell" ] && $DRY_RUN_CMD rm -f "$targetPath/quickshell/${cfg.qsConfig}"

            $DRY_RUN_CMD cp -rv "${quickshellPatched}/${cfg.qsConfig}" "$targetPath/quickshell"
            givePriv "quickshell"
          ''}

          # Material you
          $DRY_RUN_CMD mkdir -p "$targetPath/kde-material-you-colors"
          copyIfNotExist "kde-material-you-colors/config.conf"

          # Qt
          $DRY_RUN_CMD mkdir -p "$targetPath/qt5ct"
          $DRY_RUN_CMD mkdir -p "$targetPath/qt6ct"

          copyIfNotExist "qt5ct/qt5ct.conf"
          copyIfNotExist "qt6ct/qt6ct.conf"
        '';

      })
      # If cursor overwriting enabled
      (mkIf (cfg.enable && cfg.cursor.enable) {
        # TODO: Add parameters for package & theme name
        home =
          let
            macOS-Tahoe-Cursor = pkgs.stdenv.mkDerivation {
              pname = "MacTahoe-icon-theme";
              version = "1.2";

              src = pkgs.fetchzip {
                url = "https://github.com/witt-bit/MacOS-Tahoe-Cursor/releases/download/${macOS-Tahoe-Cursor.version}/MacOS-Tahoe-Cursor.zip";
                hash = "sha256-yr5GXQrtDl7aGFp84tpd6+IjgM9QVAlBMs9sAtrUPZc=";
              };

              dontCheckForBrokenSymlinks = true;

              installPhase = ''
                install -dm 0755 $out/share/icons
                cp -r ./MacOS-Tahoe-Cursor $out/share/icons/
              '';

              dontDropIconThemeCache = true;
              dontBuild = true;
              dontConfigure = true;

              meta = {
                description = "Apple MacOS Tahoe Cursor for Linux and all Windows OS.";
                homepage = "https://store.kde.org/p/2300466";
                license = lib.licenses.asl20;
                platforms = lib.platforms.linux;
              };
            };
          in
          {
            packages = [ macOS-Tahoe-Cursor ];

            pointerCursor = {
              name = "MacOS-Tahoe-Cursor";
              package = macOS-Tahoe-Cursor;

              size = cfg.cursor.size;
              x11.size = cfg.cursor.size;
              hyprcursor.size = cfg.cursor.size;

              enable = true;
              gtk.enable = true;
              x11.enable = true;
              hyprcursor.enable = true;
            };
          };
      })
      # If icons overwriting enabled
      (mkIf (cfg.enable && cfg.icons.enable) {

        # Set icon theme via dconf for GNOME/GTK apps
        dconf.settings = {
          "org/gnome/desktop/interface" = {
            icon-theme = mkDefault "${cfg.icons.dark}";
          };
        };

        home.activation.overwriteIconsTheme = config.lib.dag.entryAfter [ "writeBoundary" ] ''
          # Path to the config directory in the dotfiles source
          configPath="${dotfiles}/dots/.config"
          targetPath="$HOME/.config"

          # Kde
          $DRY_RUN_CMD sed -i '/^\[Icons\]/,/^\[/ s/^Theme=.*/Theme=${cfg.icons.dark}/' "$targetPath/kdeglobals"

          # Kde material you
          $DRY_RUN_CMD sed -i 's/^iconsdark.*/iconsdark = ${cfg.icons.dark}/' "$targetPath/kde-material-you-colors/config.conf"
          $DRY_RUN_CMD sed -i 's/^iconslight.*/iconslight = ${cfg.icons.light}/' "$targetPath/kde-material-you-colors/config.conf"

          # Qt
          for qt_conf in "$targetPath/qt5ct/qt5ct.conf" "$targetPath/qt6ct/qt6ct.conf"; do
            $DRY_RUN_CMD sed -i 's/^icon_theme=.*/icon_theme=${cfg.icons.dark}/' "$qt_conf"
          done
        '';
      })
    ];
}
