keep-open=yes
loop-file=inf

# profile=high-quality
gpu-api=opengl
fullscreen=no

keep-open=always

cscale=ewa_lanczossharp
scale=ewa_lanczossharp
dscale=mitchell

video-sync=display-resample

[big-cache]
cache=yes
demuxer-max-bytes=512MiB
demuxer-readahead-secs=20
