name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  format:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Flake format check
        continue-on-error: true
        run: nix run nixpkgs#nixfmt-tree -- --ci
